#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

/* Embedded HTML Dashboard */
const char* HTML_CONTENT = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Dynasty Hostel Management Dashboard</title>\n"
"    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n"
"    <link rel=\"stylesheet\" href=\"style.css\">\n"
"</head>\n"
"<body>\n"
"    <!-- Glow Effects -->\n"
"    <div class=\"glow glow-1\"></div>\n"
"    <div class=\"glow glow-2\"></div>\n"
"\n"
"    <!-- Login Screen -->\n"
"    <div id=\"login-screen\" class=\"login-container\">\n"
"        <div class=\"glass-card login-card\">\n"
"            <h2>Dynasty Hostel Gatekeeper</h2>\n"
"            <p class=\"subtitle\">Administrative Authentication Gateway</p>\n"
"            <div id=\"login-error\" class=\"error-msg hide\">Invalid credentials, please try again.</div>\n"
"            <form id=\"login-form\">\n"
"                <div class=\"form-group\">\n"
"                    <label>Admin Username</label>\n"
"                    <input type=\"text\" id=\"username\" required placeholder=\"Username\">\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label>Admin Password</label>\n"
"                    <input type=\"password\" id=\"password\" required placeholder=\"••••••••\">\n"
"                </div>\n"
"                <button type=\"submit\" class=\"btn-glow\">Authenticate</button>\n"
"            </form>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Main Dashboard Application -->\n"
"    <div id=\"app-screen\" class=\"app-container hide\">\n"
"        <!-- Header -->\n"
"        <header class=\"app-header\">\n"
"            <div class=\"header-brand\">\n"
"                <h1>Hostel Room Allotment System</h1>\n"
"                <p>Powered by Indian Dynasty Blocks</p>\n"
"            </div>\n"
"            <div class=\"header-user\">\n"
"                <span class=\"badge-admin\">Admin Mode: <span id=\"admin-name\">admin</span></span>\n"
"                <button id=\"logout-btn\" class=\"btn-outline btn-sm\">Logout</button>\n"
"                <button id=\"shutdown-btn\" class=\"btn-danger btn-sm\">Exit Web Console</button>\n"
"            </div>\n"
"        </header>\n"
"\n"
"        <!-- Navigation Tabs -->\n"
"        <nav class=\"app-tabs\">\n"
"            <button class=\"tab-link active\" data-tab=\"dashboard-tab\">Overview</button>\n"
"            <button class=\"tab-link\" data-tab=\"students-tab\">Student Registry</button>\n"
"            <button class=\"tab-link\" data-tab=\"rooms-tab\">Room Grid</button>\n"
"            <button class=\"tab-link\" data-tab=\"actions-tab\">Registrations & Allotment</button>\n"
"            <button class=\"tab-link\" data-tab=\"audit-tab\">System Logs</button>\n"
"            <button class=\"tab-link\" data-tab=\"settings-tab\">Settings Panel</button>\n"
"        </nav>\n"
"\n"
"        <!-- Tab Containers -->\n"
"        <main class=\"app-content\">\n"
"            <!-- Overview Tab -->\n"
"            <section id=\"dashboard-tab\" class=\"tab-content active\">\n"
"                <div class=\"metrics-row\">\n"
"                    <div class=\"metric-card glass-card\">\n"
"                        <span class=\"m-title\">Registered Students</span>\n"
"                        <span class=\"m-val\" id=\"metric-students\">-</span>\n"
"                    </div>\n"
"                    <div class=\"metric-card glass-card\">\n"
"                        <span class=\"m-title\">Beds Occupied</span>\n"
"                        <span class=\"m-val\" id=\"metric-occupied\">-</span>\n"
"                    </div>\n"
"                    <div class=\"metric-card glass-card\">\n"
"                        <span class=\"m-title\">Beds Vacant</span>\n"
"                        <span class=\"m-val\" id=\"metric-vacant\">-</span>\n"
"                    </div>\n"
"                    <div class=\"metric-card glass-card\">\n"
"                        <span class=\"m-title\">Fee Defaulters</span>\n"
"                        <span class=\"m-val\" id=\"metric-defaulters\">-</span>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"grid-2\">\n"
"                    <div class=\"glass-card\">\n"
"                        <h3>Dynasty Blocks Status</h3>\n"
"                        <div class=\"block-stats-container\" id=\"block-stats-list\">\n"
"                            <!-- Dynamically loaded block occupancy -->\n"
"                        </div>\n"
"                    </div>\n"
"                    <div class=\"glass-card\">\n"
"                        <h3>Quick System Controls</h3>\n"
"                        <p class=\"desc\">Direct actions to quickly configure databases and assets.</p>\n"
"                        <div class=\"controls-vertical\">\n"
"                            <button class=\"btn-outline tab-switch-btn\" data-tab=\"actions-tab\">Add New Student</button>\n"
"                            <button class=\"btn-outline tab-switch-btn\" data-tab=\"actions-tab\">Perform Room Allotment</button>\n"
"                            <button class=\"btn-outline tab-switch-btn\" data-tab=\"rooms-tab\">Manage Room Maintenance</button>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"            </section>\n"
"\n"
"            <!-- Student Registry Tab (Tabular Grid) -->\n"
"            <section id=\"students-tab\" class=\"tab-content\">\n"
"                <div class=\"table-actions-row\">\n"
"                    <div class=\"search-box-container\">\n"
"                        <input type=\"text\" id=\"student-search\" placeholder=\"Search by ID, Name, Course, Hostel...\">\n"
"                    </div>\n"
"                    <div class=\"filter-buttons-row\">\n"
"                        <button class=\"filter-btn active\" data-filter=\"all\">All Students</button>\n"
"                        <button class=\"filter-btn\" data-filter=\"allotted\">Allotted Only</button>\n"
"                        <button class=\"filter-btn\" data-filter=\"unallotted\">Unallotted</button>\n"
"                        <button class=\"filter-btn\" data-filter=\"defaulter\">Dues Pending</button>\n"
"                    </div>\n"
"                </div>\n"
"\n"
"                <div class=\"glass-card table-wrapper\">\n"
"                    <table class=\"system-table\" id=\"student-table\">\n"
"                        <thead>\n"
"                            <tr>\n"
"                                <th>ID</th>\n"
"                                <th>Name</th>\n"
"                                <th>Hostel Block</th>\n"
"                                <th>Room</th>\n"
"                                <th>Type</th>\n"
"                                <th>Paid</th>\n"
"                                <th>Pending</th>\n"
"                                <th class=\"text-right\">Actions</th>\n"
"                            </tr>\n"
"                        </thead>\n"
"                        <tbody id=\"student-table-body\">\n"
"                            <!-- Student rows dynamically loaded -->\n"
"                        </tbody>\n"
"                    </table>\n"
"                </div>\n"
"            </section>\n"
"\n"
"            <!-- Room Grid Tab -->\n"
"            <section id=\"rooms-tab\" class=\"tab-content\">\n"
"                <div class=\"block-selector-row\">\n"
"                    <label>Select Dynasty Block: </label>\n"
"                    <select id=\"room-block-select\" class=\"form-input select-inline\">\n"
"                        <option value=\"Maurya Block\">Maurya Block</option>\n"
"                        <option value=\"Chola Block\">Chola Block</option>\n"
"                        <option value=\"Gupta Block\">Gupta Block</option>\n"
"                        <option value=\"Mughal Block\">Mughal Block</option>\n"
"                        <option value=\"Maratha Block\">Maratha Block</option>\n"
"                        <option value=\"Vijayanagara Block\">Vijayanagara Block</option>\n"
"                    </select>\n"
"                </div>\n"
"\n"
"                <div class=\"rooms-container-grid\" id=\"rooms-layout-grid\">\n"
"                    <!-- Rooms loaded dynamically as cards -->\n"
"                </div>\n"
"            </section>\n"
"\n"
"            <!-- Actions Tab -->\n"
"            <section id=\"actions-tab\" class=\"tab-content\">\n"
"                <div class=\"grid-2\">\n"
"                    <!-- Student Registration Card -->\n"
"                    <div class=\"glass-card\">\n"
"                        <h3>Student Registration</h3>\n"
"                        <form id=\"register-form\">\n"
"                            <div class=\"section-divider-title\">Personal Details</div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Student Full Name</label>\n"
"                                    <input type=\"text\" id=\"reg-name\" required placeholder=\"John Doe\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>DOB (DD/MM/YYYY)</label>\n"
"                                    <input type=\"text\" id=\"reg-dob\" required placeholder=\"15/08/2004\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Gender</label>\n"
"                                    <select id=\"reg-gender\" class=\"form-input\">\n"
"                                        <option value=\"Male\">Male</option>\n"
"                                        <option value=\"Female\">Female</option>\n"
"                                        <option value=\"Other\">Other</option>\n"
"                                    </select>\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Aadhar (12 Digits)</label>\n"
"                                    <input type=\"text\" id=\"reg-aadhar\" required placeholder=\"123456789012\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Blood Group</label>\n"
"                                    <input type=\"text\" id=\"reg-blood\" required placeholder=\"O+\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Nationality</label>\n"
"                                    <input type=\"text\" id=\"reg-nationality\" required placeholder=\"Indian\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Email Address</label>\n"
"                                    <input type=\"email\" id=\"reg-email\" required placeholder=\"john@gmail.com\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Phone Number (10 Digits)</label>\n"
"                                    <input type=\"text\" id=\"reg-phone\" required placeholder=\"9876543210\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Religion</label>\n"
"                                    <input type=\"text\" id=\"reg-religion\" required placeholder=\"Hindu\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Caste / Category</label>\n"
"                                    <input type=\"text\" id=\"reg-caste\" required placeholder=\"General\">\n"
"                                </div>\n"
"                            </div>\n"
"\n"
"                            <div class=\"section-divider-title\">Academic Details</div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Course</label>\n"
"                                    <input type=\"text\" id=\"reg-course\" required placeholder=\"B.Tech\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Branch</label>\n"
"                                    <input type=\"text\" id=\"reg-branch\" required placeholder=\"CSE\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Semester</label>\n"
"                                    <input type=\"text\" id=\"reg-semester\" required placeholder=\"III\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Roll Number</label>\n"
"                                    <input type=\"text\" id=\"reg-roll\" required placeholder=\"2024CSE001\">\n"
"                                </div>\n"
"                            </div>\n"
"\n"
"                            <div class=\"section-divider-title\">Parent & Address Details</div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Father's Name</label>\n"
"                                    <input type=\"text\" id=\"reg-father\" required placeholder=\"Father Doe\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Mother's Name</label>\n"
"                                    <input type=\"text\" id=\"reg-mother\" required placeholder=\"Mother Doe\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Parent Phone</label>\n"
"                                    <input type=\"text\" id=\"reg-parent-phone\" required placeholder=\"9876543211\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Parent Email</label>\n"
"                                    <input type=\"email\" id=\"reg-parent-email\" required placeholder=\"father@gmail.com\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Parent Occupation</label>\n"
"                                    <input type=\"text\" id=\"reg-parent-occ\" required placeholder=\"Business\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Parent Income</label>\n"
"                                    <input type=\"text\" id=\"reg-parent-income\" required placeholder=\"1200000\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Guardian Name</label>\n"
"                                    <input type=\"text\" id=\"reg-guard-name\" required placeholder=\"Guardian Doe\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Guardian Relation</label>\n"
"                                    <input type=\"text\" id=\"reg-guard-rel\" required placeholder=\"Uncle\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Guardian Phone</label>\n"
"                                    <input type=\"text\" id=\"reg-guard-phone\" required placeholder=\"9876543212\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Guardian Address</label>\n"
"                                    <input type=\"text\" id=\"reg-guard-addr\" required placeholder=\"Guardian Residence\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-group\">\n"
"                                <label>Street Address</label>\n"
"                                <input type=\"text\" id=\"reg-addr\" required placeholder=\"Street Road No.\">\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>City</label>\n"
"                                    <input type=\"text\" id=\"reg-city\" required placeholder=\"City\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>State</label>\n"
"                                    <input type=\"text\" id=\"reg-state\" required placeholder=\"State\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Pincode (6 digits)</label>\n"
"                                    <input type=\"text\" id=\"reg-pincode\" required placeholder=\"560001\">\n"
"                                </div>\n"
"                            </div>\n"
"\n"
"                            <button type=\"submit\" class=\"btn-glow\">Register Student</button>\n"
"                        </form>\n"
"                    </div>\n"
"\n"
"                    <!-- Room Allotment Card -->\n"
"                    <div class=\"glass-card height-fit\">\n"
"                        <h3>Room Allotment Panel</h3>\n"
"                        <form id=\"allot-form\">\n"
"                            <div class=\"form-group\">\n"
"                                <label>Select Student ID</label>\n"
"                                <select id=\"allot-student-select\" class=\"form-input\" required>\n"
"                                    <option value=\"\">-- Select Unallotted Student --</option>\n"
"                                </select>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Select Block</label>\n"
"                                    <select id=\"allot-block-select\" class=\"form-input\" required>\n"
"                                        <option value=\"Maurya Block\">Maurya Block</option>\n"
"                                        <option value=\"Chola Block\">Chola Block</option>\n"
"                                        <option value=\"Gupta Block\">Gupta Block</option>\n"
"                                        <option value=\"Mughal Block\">Mughal Block</option>\n"
"                                        <option value=\"Maratha Block\">Maratha Block</option>\n"
"                                        <option value=\"Vijayanagara Block\">Vijayanagara Block</option>\n"
"                                    </select>\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Room Type Preference</label>\n"
"                                    <select id=\"allot-type-select\" class=\"form-input\" required>\n"
"                                        <option value=\"Single\">Single</option>\n"
"                                        <option value=\"Double\">Double</option>\n"
"                                        <option value=\"Triple\">Triple</option>\n"
"                                    </select>\n"
"                                </div>\n"
"                            </div>\n"
"                            <div class=\"form-group\">\n"
"                                <label>Select Available Room Number</label>\n"
"                                <select id=\"allot-room-select\" class=\"form-input\" required>\n"
"                                    <option value=\"\">-- Select Room --</option>\n"
"                                </select>\n"
"                            </div>\n"
"                            <div class=\"form-row\">\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Allotment Date (DD/MM/YYYY)</label>\n"
"                                    <input type=\"text\" id=\"allot-date\" required placeholder=\"26/05/2026\">\n"
"                                </div>\n"
"                                <div class=\"form-group\">\n"
"                                    <label>Fee Paid upfront (INR)</label>\n"
"                                    <input type=\"text\" id=\"allot-paid\" required placeholder=\"10000\">\n"
"                                </div>\n"
"                            </div>\n"
"                            <button type=\"submit\" class=\"btn-glow\">Complete Allotment</button>\n"
"                        </form>\n"
"                    </div>\n"
"                </div>\n"
"            </section>\n"
"\n"
"            <!-- System Logs Tab -->\n"
"            <section id=\"audit-tab\" class=\"tab-content\">\n"
"                <div class=\"glass-card\">\n"
"                    <div class=\"table-header-flex\">\n"
"                        <h3>System Security Audit Log</h3>\n"
"                        <button id=\"refresh-audit-btn\" class=\"btn-outline btn-sm\">Refresh Logs</button>\n"
"                    </div>\n"
"                    <div class=\"audit-container-list\" id=\"audit-log-list\">\n"
"                        <!-- Audit log items loaded dynamically -->\n"
"                    </div>\n"
"                </div>\n"
"            </section>\n"
"\n"
"            <!-- Settings Panel Tab -->\n"
"            <section id=\"settings-tab\" class=\"tab-content\">\n"
"                <div class=\"grid-2\">\n"
"                    <div class=\"glass-card\">\n"
"                        <h3>Edit Room Fee Configurations</h3>\n"
"                        <form id=\"config-form\">\n"
"                            <div class=\"form-group\">\n"
"                                <label>Single Room Base Fee (INR)</label>\n"
"                                <input type=\"text\" id=\"cfg-single\" required>\n"
"                            </div>\n"
"                            <div class=\"form-group\">\n"
"                                <label>Double Room Base Fee (INR)</label>\n"
"                                <input type=\"text\" id=\"cfg-double\" required>\n"
"                            </div>\n"
"                            <div class=\"form-group\">\n"
"                                <label>Triple Room Base Fee (INR)</label>\n"
"                                <input type=\"text\" id=\"cfg-triple\" required>\n"
"                            </div>\n"
"                            <button type=\"submit\" class=\"btn-glow\">Save Fee Structure</button>\n"
"                        </form>\n"
"                    </div>\n"
"\n"
"                    <div class=\"glass-card\">\n"
"                        <h3>Change Admin Password</h3>\n"
"                        <form id=\"password-form\">\n"
"                            <div class=\"form-group\">\n"
"                                <label>Current Admin Password</label>\n"
"                                <input type=\"password\" id=\"pwd-current\" required>\n"
"                            </div>\n"
"                            <div class=\"form-group\">\n"
"                                <label>New Password (min. 6 chars)</label>\n"
"                                <input type=\"password\" id=\"pwd-new\" required>\n"
"                            </div>\n"
"                            <div class=\"form-group\">\n"
"                                <label>Confirm New Password</label>\n"
"                                <input type=\"password\" id=\"pwd-confirm\" required>\n"
"                            </div>\n"
"                            <button type=\"submit\" class=\"btn-glow\">Update Password</button>\n"
"                        </form>\n"
"\n"
"                        <div class=\"critical-zone-divider\"></div>\n"
"                        <h3 class=\"critical-text\">CRITICAL: Administrative Wipes</h3>\n"
"                        <p class=\"desc\">Resetting all databases will vacate all students, reset block allocations, and revert settings to default.</p>\n"
"                        <button id=\"wipe-database-btn\" class=\"btn-danger\">Wipe Databases (WIPE)</button>\n"
"                    </div>\n"
"                </div>\n"
"            </section>\n"
"        </main>\n"
"    </div>\n"
"\n"
"    <!-- Dossier Detail Modal -->\n"
"    <div id=\"dossier-modal\" class=\"modal-overlay hide\">\n"
"        <div class=\"glass-card modal-card\">\n"
"            <div class=\"modal-header\">\n"
"                <h2 id=\"dos-title\">Student Profile Dossier</h2>\n"
"                <button class=\"close-modal-btn\" onclick=\"closeDossier()\">×</button>\n"
"            </div>\n"
"            <div class=\"modal-body\" id=\"dossier-body-content\">\n"
"                <!-- Dossier metadata loaded dynamically -->\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Room Transfer Modal -->\n"
"    <div id=\"transfer-modal\" class=\"modal-overlay hide\">\n"
"        <div class=\"glass-card modal-card-sm\">\n"
"            <div class=\"modal-header\">\n"
"                <h2>Transfer Student Room</h2>\n"
"                <button class=\"close-modal-btn\" onclick=\"closeTransfer()\">×</button>\n"
"            </div>\n"
"            <form id=\"transfer-modal-form\">\n"
"                <input type=\"hidden\" id=\"xfr-student-id\">\n"
"                <div class=\"form-group\">\n"
"                    <label>Student ID / Name</label>\n"
"                    <div id=\"xfr-student-display\" class=\"readonly-display-box\">STU-001 - Rahul</div>\n"
"                </div>\n"
"                <div class=\"form-row\">\n"
"                    <div class=\"form-group\">\n"
"                        <label>Select NEW Block</label>\n"
"                        <select id=\"xfr-block-select\" class=\"form-input\" required>\n"
"                            <option value=\"Maurya Block\">Maurya Block</option>\n"
"                            <option value=\"Chola Block\">Chola Block</option>\n"
"                            <option value=\"Gupta Block\">Gupta Block</option>\n"
"                            <option value=\"Mughal Block\">Mughal Block</option>\n"
"                            <option value=\"Maratha Block\">Maratha Block</option>\n"
"                            <option value=\"Vijayanagara Block\">Vijayanagara Block</option>\n"
"                        </select>\n"
"                    </div>\n"
"                    <div class=\"form-group\">\n"
"                        <label>Select Room Type</label>\n"
"                        <select id=\"xfr-type-select\" class=\"form-input\" required>\n"
"                            <option value=\"Single\">Single</option>\n"
"                            <option value=\"Double\">Double</option>\n"
"                            <option value=\"Triple\">Triple</option>\n"
"                        </select>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label>Select Available Room</label>\n"
"                    <select id=\"xfr-room-select\" class=\"form-input\" required>\n"
"                        <option value=\"\">-- Select Room --</option>\n"
"                    </select>\n"
"                </div>\n"
"                <button type=\"submit\" class=\"btn-glow\">Apply Transfer</button>\n"
"            </form>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <!-- Room Vacate Modal -->\n"
"    <div id=\"vacate-modal\" class=\"modal-overlay hide\">\n"
"        <div class=\"glass-card modal-card-sm\">\n"
"            <div class=\"modal-header\">\n"
"                <h2>Vacate Student Room</h2>\n"
"                <button class=\"close-modal-btn\" onclick=\"closeVacate()\">×</button>\n"
"            </div>\n"
"            <form id=\"vacate-modal-form\">\n"
"                <input type=\"hidden\" id=\"vac-student-id\">\n"
"                <div class=\"form-group\">\n"
"                    <label>Student ID / Name</label>\n"
"                    <div id=\"vac-student-display\" class=\"readonly-display-box\">STU-001 - Rahul</div>\n"
"                </div>\n"
"                <div class=\"form-group\">\n"
"                    <label>Enter Checkout Date (DD/MM/YYYY)</label>\n"
"                    <input type=\"text\" id=\"vac-date\" required placeholder=\"26/05/2026\">\n"
"                </div>\n"
"                <button type=\"submit\" class=\"btn-danger\">Confirm Vacate</button>\n"
"            </form>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script src=\"app.js\"></script>\n"
"</body>\n"
"</html>\n";

/* Embedded CSS Theme Styles */
const char* CSS_CONTENT = 
"* {\n"
"    box-sizing: border-box;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    font-family: 'Inter', -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
"}\n"
"body {\n"
"    background-color: #0c0f17;\n"
"    color: #e2e8f0;\n"
"    min-height: 100vh;\n"
"    overflow-x: hidden;\n"
"    position: relative;\n"
"}\n"
"/* Glowing Background Blobs */\n"
".glow {\n"
"    position: absolute;\n"
"    width: 40vw;\n"
"    height: 40vw;\n"
"    border-radius: 50%;\n"
"    filter: blur(140px);\n"
"    opacity: 0.12;\n"
"    z-index: -1;\n"
"    pointer-events: none;\n"
"}\n"
".glow-1 {\n"
"    background: radial-gradient(circle, #06b6d4 0%, rgba(6,182,212,0) 70%);\n"
"    top: -10vw;\n"
"    left: -10vw;\n"
"}\n"
".glow-2 {\n"
"    background: radial-gradient(circle, #8b5cf6 0%, rgba(139,92,246,0) 70%);\n"
"    bottom: -10vw;\n"
"    right: -10vw;\n"
"}\n"
"/* Glassmorphic Styles */\n"
".glass-card {\n"
"    background: rgba(20, 26, 38, 0.65);\n"
"    backdrop-filter: blur(16px);\n"
"    -webkit-backdrop-filter: blur(16px);\n"
"    border: 1px solid rgba(255, 255, 255, 0.05);\n"
"    border-radius: 12px;\n"
"    padding: 24px;\n"
"    box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.47);\n"
"    margin-bottom: 20px;\n"
"}\n"
"/* Login Card */\n"
".login-container {\n"
"    display: flex;\n"
"    justify-content: center;\n"
"    align-items: center;\n"
"    min-height: 100vh;\n"
"}\n"
".login-card {\n"
"    width: 100%;\n"
"    max-width: 420px;\n"
"    border: 1px solid rgba(6, 182, 212, 0.2);\n"
"}\n"
"h2 {\n"
"    font-weight: 700;\n"
"    font-size: 24px;\n"
"    margin-bottom: 6px;\n"
"    background: linear-gradient(135deg, #06b6d4 0%, #a5f3fc 100%);\n"
"    -webkit-background-clip: text;\n"
"    -webkit-text-fill-color: transparent;\n"
"    text-shadow: 0 2px 10px rgba(6, 182, 212, 0.1);\n"
"}\n"
".subtitle {\n"
"    color: #94a3b8;\n"
"    font-size: 14px;\n"
"    margin-bottom: 24px;\n"
"}\n"
"/* Forms */\n"
".form-group {\n"
"    margin-bottom: 18px;\n"
"}\n"
"label {\n"
"    display: block;\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #94a3b8;\n"
"    margin-bottom: 8px;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"input[type=\"text\"],\n"
"input[type=\"password\"],\n"
"input[type=\"email\"],\n"
"select {\n"
"    width: 100%;\n"
"    padding: 12px 16px;\n"
"    background: rgba(13, 17, 26, 0.7);\n"
"    border: 1px solid rgba(255, 255, 255, 0.1);\n"
"    border-radius: 8px;\n"
"    color: #e2e8f0;\n"
"    font-size: 14px;\n"
"    outline: none;\n"
"    transition: border-color 0.2s, box-shadow 0.2s;\n"
"}\n"
"input[type=\"text\"]:focus,\n"
"input[type=\"password\"]:focus,\n"
"input[type=\"email\"]:focus,\n"
"select:focus {\n"
"    border-color: #06b6d4;\n"
"    box-shadow: 0 0 10px rgba(6, 182, 212, 0.2);\n"
"}\n"
".form-row {\n"
"    display: flex;\n"
"    gap: 16px;\n"
"}\n"
".form-row .form-group {\n"
"    flex: 1;\n"
"}\n"
"/* Buttons */\n"
"button {\n"
"    cursor: pointer;\n"
"    border: none;\n"
"    outline: none;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s;\n"
"}\n"
".btn-glow {\n"
"    width: 100%;\n"
"    padding: 14px;\n"
"    background: linear-gradient(135deg, #06b6d4 0%, #0891b2 100%);\n"
"    color: #ffffff;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 4px 15px rgba(6, 182, 212, 0.3);\n"
"}\n"
".btn-glow:hover {\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 6px 20px rgba(6, 182, 212, 0.5);\n"
"}\n"
".btn-outline {\n"
"    background: transparent;\n"
"    border: 1px solid rgba(6, 182, 212, 0.4);\n"
"    color: #22d3ee;\n"
"    padding: 10px 20px;\n"
"    border-radius: 8px;\n"
"}\n"
".btn-outline:hover {\n"
"    background: rgba(6, 182, 212, 0.1);\n"
"    color: #ffffff;\n"
"}\n"
".btn-danger {\n"
"    background: rgba(239, 68, 68, 0.2);\n"
"    border: 1px solid #ef4444;\n"
"    color: #fca5a5;\n"
"    padding: 10px 20px;\n"
"    border-radius: 8px;\n"
"}\n"
".btn-danger:hover {\n"
"    background: #ef4444;\n"
"    color: #ffffff;\n"
"}\n"
".btn-sm {\n"
"    padding: 6px 12px;\n"
"    font-size: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"/* App layout */\n"
".app-container {\n"
"    max-width: 1200px;\n"
"    margin: 0 auto;\n"
"    padding: 24px;\n"
"}\n"
".app-header {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    padding-bottom: 20px;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.05);\n"
"    margin-bottom: 24px;\n"
"}\n"
".header-brand p {\n"
"    color: #06b6d4;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
".header-user {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 12px;\n"
"}\n"
".badge-admin {\n"
"    background: rgba(255, 255, 255, 0.05);\n"
"    border: 1px solid rgba(255, 255, 255, 0.1);\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"    color: #cbd5e1;\n"
"}\n"
"/* Tabs Navigation */\n"
".app-tabs {\n"
"    display: flex;\n"
"    gap: 8px;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.05);\n"
"    padding-bottom: 12px;\n"
"    margin-bottom: 24px;\n"
"    overflow-x: auto;\n"
"}\n"
".tab-link {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #94a3b8;\n"
"    padding: 10px 18px;\n"
"    border-radius: 8px;\n"
"    font-weight: 500;\n"
"    white-space: nowrap;\n"
"}\n"
".tab-link.active {\n"
"    background: rgba(6, 182, 212, 0.15);\n"
"    color: #22d3ee;\n"
"    border: 1px solid rgba(6, 182, 212, 0.2);\n"
"}\n"
".tab-content {\n"
"    display: none;\n"
"}\n"
".tab-content.active {\n"
"    display: block;\n"
"    animation: fadeIn 0.3s ease-in-out;\n"
"}\n"
"/* Metrics */\n"
".metrics-row {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\n"
"    gap: 20px;\n"
"    margin-bottom: 24px;\n"
"}\n"
".metric-card {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    justify-content: center;\n"
"}\n"
".m-title {\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    color: #94a3b8;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.5px;\n"
"    margin-bottom: 8px;\n"
"}\n"
".m-val {\n"
"    font-size: 32px;\n"
"    font-weight: 700;\n"
"    color: #ffffff;\n"
"}\n"
".grid-2 {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));\n"
"    gap: 20px;\n"
"}\n"
".controls-vertical {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"    gap: 12px;\n"
"    margin-top: 16px;\n"
"}\n"
".controls-vertical button {\n"
"    text-align: left;\n"
"}\n"
".desc {\n"
"    color: #cbd5e1;\n"
"    font-size: 14px;\n"
"    margin-bottom: 12px;\n"
"}\n"
"/* Tables */\n"
".table-actions-row {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    margin-bottom: 20px;\n"
"    flex-wrap: wrap;\n"
"    gap: 16px;\n"
"}\n"
".search-box-container {\n"
"    flex: 1;\n"
"    max-width: 400px;\n"
"    min-width: 250px;\n"
"}\n"
".filter-buttons-row {\n"
"    display: flex;\n"
"    gap: 6px;\n"
"}\n"
".filter-btn {\n"
"    background: rgba(255, 255, 255, 0.03);\n"
"    border: 1px solid rgba(255, 255, 255, 0.07);\n"
"    color: #94a3b8;\n"
"    padding: 8px 14px;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"}\n"
".filter-btn.active {\n"
"    background: rgba(6, 182, 212, 0.1);\n"
"    border-color: #06b6d4;\n"
"    color: #ffffff;\n"
"}\n"
".table-wrapper {\n"
"    padding: 0;\n"
"    overflow-x: auto;\n"
"}\n"
".system-table {\n"
"    width: 100%;\n"
"    border-collapse: collapse;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"}\n"
".system-table th,\n"
"border-collapse: collapse;\n"
".system-table td {\n"
"    padding: 14px 20px;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 0.05);\n"
"}\n"
".system-table th {\n"
"    background: rgba(255, 255, 255, 0.02);\n"
"    color: #cbd5e1;\n"
"    font-weight: 600;\n"
"    text-transform: uppercase;\n"
"    font-size: 11px;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
".system-table tr:hover td {\n"
"    background: rgba(255, 255, 255, 0.015);\n"
"}\n"
".actions-flex {\n"
"    display: flex;\n"
"    gap: 8px;\n"
"    justify-content: flex-end;\n"
"}\n"
"/* Rooms */\n"
".block-selector-row {\n"
"    display: flex;\n"
"    align-items: center;\n"
"    gap: 12px;\n"
"    margin-bottom: 24px;\n"
"}\n"
".select-inline {\n"
"    width: auto;\n"
"    min-width: 200px;\n"
"}\n"
".rooms-container-grid {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));\n"
"    gap: 20px;\n"
"}\n"
".room-card {\n"
"    background: rgba(13, 17, 26, 0.5);\n"
"    border: 1px solid rgba(255, 255, 255, 0.05);\n"
"    border-radius: 10px;\n"
"    padding: 18px;\n"
"    text-align: center;\n"
"    transition: transform 0.2s, border-color 0.2s;\n"
"    position: relative;\n"
"}\n"
".room-card:hover {\n"
"    transform: translateY(-2px);\n"
"}\n"
".room-card.state-vacant {\n"
"    border-color: rgba(34, 197, 94, 0.2);\n"
"}\n"
".room-card.state-vacant:hover {\n"
"    border-color: #22c55e;\n"
"}\n"
".room-card.state-full {\n"
"    border-color: rgba(234, 179, 8, 0.2);\n"
"}\n"
".room-card.state-full:hover {\n"
"    border-color: #eab308;\n"
"}\n"
".room-card.state-maint {\n"
"    border-color: rgba(239, 68, 68, 0.2);\n"
"    background: rgba(239, 68, 68, 0.02);\n"
"}\n"
".room-card.state-maint:hover {\n"
"    border-color: #ef4444;\n"
"}\n"
".room-number {\n"
"    font-size: 20px;\n"
"    font-weight: 700;\n"
"    margin-bottom: 4px;\n"
"}\n"
".room-type-badge {\n"
"    font-size: 11px;\n"
"    font-weight: 600;\n"
"    text-transform: uppercase;\n"
"    color: #cbd5e1;\n"
"    background: rgba(255, 255, 255, 0.05);\n"
"    padding: 2px 8px;\n"
"    border-radius: 12px;\n"
"    display: inline-block;\n"
"    margin-bottom: 12px;\n"
"}\n"
".room-occupancy-text {\n"
"    font-size: 13px;\n"
"    color: #cbd5e1;\n"
"    margin-bottom: 14px;\n"
"}\n"
"/* Audits */\n"
".table-header-flex {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    margin-bottom: 18px;\n"
"}\n"
".audit-container-list {\n"
"    max-height: 450px;\n"
"    overflow-y: auto;\n"
"    font-family: monospace;\n"
"    font-size: 13px;\n"
"    background: rgba(13, 17, 26, 0.7);\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.05);\n"
"}\n"
".audit-item {\n"
"    padding: 8px 0;\n"
"    border-bottom: 1px solid rgba(255,255,255,0.03);\n"
"    white-space: pre-wrap;\n"
"}\n"
"/* Modals */\n"
".modal-overlay {\n"
"    position: fixed;\n"
"    top: 0;\n"
"    left: 0;\n"
"    width: 100vw;\n"
"    height: 100vh;\n"
"    background: rgba(12, 15, 23, 0.85);\n"
"    z-index: 100;\n"
"    display: flex;\n"
"    justify-content: center;\n"
"    align-items: center;\n"
"}\n"
".modal-card {\n"
"    width: 90%;\n"
"    max-width: 700px;\n"
"    max-height: 90vh;\n"
"    overflow-y: auto;\n"
"    border: 1px solid rgba(6, 182, 212, 0.3);\n"
"}\n"
".modal-card-sm {\n"
"    width: 90%;\n"
"    max-width: 480px;\n"
"    border: 1px solid rgba(6, 182, 212, 0.3);\n"
"}\n"
".modal-header {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    margin-bottom: 20px;\n"
"    border-bottom: 1px solid rgba(255,255,255,0.05);\n"
"    padding-bottom: 10px;\n"
"}\n"
".close-modal-btn {\n"
"    background: transparent;\n"
"    font-size: 28px;\n"
"    color: #94a3b8;\n"
"}\n"
".close-modal-btn:hover {\n"
"    color: #ef4444;\n"
"}\n"
"/* Dossier sheets formatting */\n"
".dos-section {\n"
"    margin-bottom: 16px;\n"
"}\n"
".dos-section-title {\n"
"    font-size: 13px;\n"
"    font-weight: 700;\n"
"    text-transform: uppercase;\n"
"    color: #06b6d4;\n"
"    margin-bottom: 10px;\n"
"    border-bottom: 1px solid rgba(6,182,212,0.1);\n"
"    padding-bottom: 4px;\n"
"}\n"
".dos-grid-3 {\n"
"    display: grid;\n"
"    grid-template-columns: 1fr 1fr 1fr;\n"
"    gap: 12px;\n"
"    font-size: 13px;\n"
"    margin-bottom: 12px;\n"
"}\n"
".dos-grid-2 {\n"
"    display: grid;\n"
"    grid-template-columns: 1fr 1fr;\n"
"    gap: 12px;\n"
"    font-size: 13px;\n"
"    margin-bottom: 12px;\n"
"}\n"
".dos-lbl {\n"
"    color: #94a3b8;\n"
"    font-weight: 500;\n"
"}\n"
".dos-val {\n"
"    color: #cbd5e1;\n"
"    font-weight: 600;\n"
"}\n"
".readonly-display-box {\n"
"    background: rgba(13, 17, 26, 0.7);\n"
"    padding: 12px;\n"
"    border: 1px solid rgba(255,255,255,0.05);\n"
"    border-radius: 8px;\n"
"    color: #cbd5e1;\n"
"    font-size: 14px;\n"
"}\n"
"/* Dynamic Progress bars */\n"
".block-stat-item {\n"
"    margin-bottom: 14px;\n"
"}\n"
".block-stat-label-row {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    font-size: 13px;\n"
"    margin-bottom: 6px;\n"
"}\n"
".block-bar-outer {\n"
"    width: 100%;\n"
"    height: 8px;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border-radius: 4px;\n"
"    overflow: hidden;\n"
"}\n"
".block-bar-inner {\n"
"    height: 100%;\n"
"    background: linear-gradient(90deg, #06b6d4, #8b5cf6);\n"
"    border-radius: 4px;\n"
"    width: 0%;\n"
"    transition: width 0.4s ease-out;\n"
"}\n"
"/* Formatting tags */\n"
".text-right { text-align: right; }\n"
".text-center { text-align: center; }\n"
".text-success { color: #4ade80; }\n"
".text-warning { color: #facc15; }\n"
".text-danger { color: #fca5a5; }\n"
".section-divider-title {\n"
"    font-size: 12px;\n"
"    font-weight: 700;\n"
"    color: #8b5cf6;\n"
"    text-transform: uppercase;\n"
"    margin: 20px 0 10px 0;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
".critical-zone-divider {\n"
"    height: 1px;\n"
"    background: rgba(239, 68, 68, 0.2);\n"
"    margin: 24px 0;\n"
"}\n"
".critical-text { color: #fca5a5; }\n"
".height-fit { height: fit-content; }\n"
".hide { display: none !important; }\n"
".error-msg {\n"
"    background: rgba(239, 68, 68, 0.1);\n"
"    border: 1px solid #ef4444;\n"
"    color: #fca5a5;\n"
"    padding: 12px;\n"
"    border-radius: 8px;\n"
"    margin-bottom: 16px;\n"
"    font-size: 14px;\n"
"}\n"
"@keyframes fadeIn {\n"
"    from { opacity: 0; transform: translateY(4px); }\n"
"    to { opacity: 1; transform: translateY(0); }\n"
"}\n"
"";

/* Embedded Javascript Dashboard Controller */
const char* JS_CONTENT = 
"// State Object\n"
"const state = {\n"
"    students: [],\n"
"    rooms: [],\n"
"    config: {},\n"
"    audit: [],\n"
"    user: null\n"
"};\n"
"\n"
"// Initialization\n"
"document.addEventListener('DOMContentLoaded', () => {\n"
"    initApp();\n"
"});\n"
"\n"
"function initApp() {\n"
"    // Form Submits\n"
"    document.getElementById('login-form').addEventListener('submit', handleLogin);\n"
"    document.getElementById('register-form').addEventListener('submit', handleRegister);\n"
"    document.getElementById('allot-form').addEventListener('submit', handleAllot);\n"
"    document.getElementById('transfer-modal-form').addEventListener('submit', handleTransfer);\n"
"    document.getElementById('vacate-modal-form').addEventListener('submit', handleVacate);\n"
"    document.getElementById('config-form').addEventListener('submit', handleConfigUpdate);\n"
"    document.getElementById('password-form').addEventListener('submit', handlePasswordChange);\n"
"    document.getElementById('wipe-database-btn').addEventListener('click', handleDatabaseWipe);\n"
"    document.getElementById('logout-btn').addEventListener('click', handleLogout);\n"
"    document.getElementById('shutdown-btn').addEventListener('click', handleShutdown);\n"
"    document.getElementById('refresh-audit-btn').addEventListener('click', loadAuditLogs);\n"
"    \n"
"    // Search / Filter Listeners\n"
"    document.getElementById('student-search').addEventListener('input', renderStudentsTable);\n"
"    document.getElementById('room-block-select').addEventListener('change', renderRoomsGrid);\n"
"    document.getElementById('allot-block-select').addEventListener('change', updateAllotRoomDropdown);\n"
"    document.getElementById('allot-type-select').addEventListener('change', updateAllotRoomDropdown);\n"
"    document.getElementById('xfr-block-select').addEventListener('change', updateTransferRoomDropdown);\n"
"    document.getElementById('xfr-type-select').addEventListener('change', updateTransferRoomDropdown);\n"
"\n"
"    // Tab link bindings\n"
"    document.querySelectorAll('.tab-link').forEach(link => {\n"
"        link.addEventListener('click', (e) => {\n"
"            switchTab(e.target.getAttribute('data-tab'));\n"
"        });\n"
"    });\n"
"\n"
"    document.querySelectorAll('.tab-switch-btn').forEach(btn => {\n"
"        btn.addEventListener('click', (e) => {\n"
"            switchTab(e.target.getAttribute('data-tab'));\n"
"        });\n"
"    });\n"
"\n"
"    document.querySelectorAll('.filter-btn').forEach(btn => {\n"
"        btn.addEventListener('click', (e) => {\n"
"            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));\n"
"            e.target.classList.add('active');\n"
"            renderStudentsTable();\n"
"        });\n"
"    });\n"
"\n"
"    // Load initially to check local session\n"
"    const cachedUser = localStorage.getItem('dynasty_admin');\n"
"    if (cachedUser) {\n"
"        state.user = cachedUser;\n"
"        showAppScreen();\n"
"    } else {\n"
"        showLoginScreen();\n"
"    }\n"
"}\n"
"\n"
"// Navigation\n"
"function switchTab(tabId) {\n"
"    document.querySelectorAll('.tab-link').forEach(link => {\n"
"        if (link.getAttribute('data-tab') === tabId) link.classList.add('active');\n"
"        else link.classList.remove('active');\n"
"    });\n"
"    document.querySelectorAll('.tab-content').forEach(content => {\n"
"        if (content.id === tabId) content.classList.add('active');\n"
"        else content.classList.remove('active');\n"
"    });\n"
"    \n"
"    // Context triggers\n"
"    if (tabId === 'dashboard-tab') loadMetrics();\n"
"    else if (tabId === 'students-tab') loadStudents();\n"
"    else if (tabId === 'rooms-tab') loadRooms();\n"
"    else if (tabId === 'actions-tab') { loadStudents(); loadRooms(); }\n"
"    else if (tabId === 'audit-tab') loadAuditLogs();\n"
"    else if (tabId === 'settings-tab') loadConfigData();\n"
"}\n"
"\n"
"function showLoginScreen() {\n"
"    document.getElementById('login-screen').classList.remove('hide');\n"
"    document.getElementById('app-screen').classList.add('hide');\n"
"}\n"
"\n"
"function showAppScreen() {\n"
"    document.getElementById('login-screen').classList.add('hide');\n"
"    document.getElementById('app-screen').classList.remove('hide');\n"
"    document.getElementById('admin-name').innerText = state.user;\n"
"    switchTab('dashboard-tab');\n"
"}\n"
"\n"
"// APIs fetching\n"
"function loadMetrics() {\n"
"    fetch('/api/students')\n"
"        .then(res => res.json())\n"
"        .then(students => {\n"
"            state.students = students;\n"
"            document.getElementById('metric-students').innerText = students.length;\n"
"            \n"
"            let activeResidents = students.filter(s => s.isAllotted).length;\n"
"            document.getElementById('metric-occupied').innerText = activeResidents;\n"
"            \n"
"            let duesPending = students.filter(s => s.isAllotted && s.feePending > 0).length;\n"
"            document.getElementById('metric-defaulters').innerText = duesPending;\n"
"\n"
"            return fetch('/api/rooms');\n"
"        })\n"
"        .then(res => res.json())\n"
"        .then(rooms => {\n"
"            state.rooms = rooms;\n"
"            \n"
"            let totalBeds = rooms.reduce((acc, r) => acc + r.capacity, 0);\n"
"            let occupiedBeds = rooms.reduce((acc, r) => acc + r.occupancy, 0);\n"
"            document.getElementById('metric-vacant').innerText = totalBeds - occupiedBeds;\n"
"            \n"
"            renderBlockStats(rooms);\n"
"        })\n"
"        .catch(err => console.error('Error fetching metrics', err));\n"
"}\n"
"\n"
"function loadStudents() {\n"
"    fetch('/api/students')\n"
"        .then(res => res.json())\n"
"        .then(students => {\n"
"            state.students = students;\n"
"            renderStudentsTable();\n"
"            updateStudentAllotDropdown();\n"
"        });\n"
"}\n"
"\n"
"function loadRooms() {\n"
"    fetch('/api/rooms')\n"
"        .then(res => res.json())\n"
"        .then(rooms => {\n"
"            state.rooms = rooms;\n"
"            renderRoomsGrid();\n"
"            updateAllotRoomDropdown();\n"
"        });\n"
"}\n"
"\n"
"function loadConfigData() {\n"
"    fetch('/api/config')\n"
"        .then(res => res.json())\n"
"        .then(cfg => {\n"
"            state.config = cfg;\n"
"            document.getElementById('cfg-single').value = cfg.feeSingle;\n"
"            document.getElementById('cfg-double').value = cfg.feeDouble;\n"
"            document.getElementById('cfg-triple').value = cfg.feeTriple;\n"
"        });\n"
"}\n"
"\n"
"function loadAuditLogs() {\n"
"    fetch('/api/audit')\n"
"        .then(res => res.json())\n"
"        .then(audit => {\n"
"            state.audit = audit;\n"
"            const container = document.getElementById('audit-log-list');\n"
"            container.innerHTML = '';\n"
"            if (audit.length === 0) {\n"
"                container.innerHTML = '<div class=\"text-center text-warning\">No logs available.</div>';\n"
"                return;\n"
"            }\n"
"            audit.reverse().forEach(line => {\n"
"                const div = document.createElement('div');\n"
"                div.className = 'audit-item';\n"
"                div.innerText = line;\n"
"                container.appendChild(div);\n"
"            });\n"
"        });\n"
"}\n"
"\n"
"// Rendering UI Components\n"
"function renderBlockStats(rooms) {\n"
"    const blocks = [\n"
"        \"Maurya Block\", \"Chola Block\", \"Gupta Block\", \n"
"        \"Mughal Block\", \"Maratha Block\", \"Vijayanagara Block\"\n"
"    ];\n"
"    const list = document.getElementById('block-stats-list');\n"
"    list.innerHTML = '';\n"
"    \n"
"    blocks.forEach(blockName => {\n"
"        const blockRooms = rooms.filter(r => r.hostelName === blockName);\n"
"        const cap = blockRooms.reduce((acc, r) => acc + r.capacity, 0);\n"
"        const occ = blockRooms.reduce((acc, r) => acc + r.occupancy, 0);\n"
"        const pct = cap > 0 ? (occ * 100) / cap : 0;\n"
"        \n"
"        const item = document.createElement('div');\n"
"        item.className = 'block-stat-item';\n"
"        item.innerHTML = `\n"
"            <div class=\"block-stat-label-row\">\n"
"                <span>${blockName}</span>\n"
"                <span>Beds: ${occ}/${cap} (${pct.toFixed(0)}%)</span>\n"
"            </div>\n"
"            <div class=\"block-bar-outer\">\n"
"                <div class=\"block-bar-inner\" style=\"width: ${pct}%\"></div>\n"
"            </div>\n"
"        `;\n"
"        list.appendChild(item);\n"
"    });\n"
"}\n"
"\n"
"function renderStudentsTable() {\n"
"    const query = document.getElementById('student-search').value.toLowerCase();\n"
"    const activeFilterBtn = document.querySelector('.filter-btn.active');\n"
"    const filter = activeFilterBtn ? activeFilterBtn.getAttribute('data-filter') : 'all';\n"
"    \n"
"    const tbody = document.getElementById('student-table-body');\n"
"    tbody.innerHTML = '';\n"
"    \n"
"    let filtered = state.students.filter(s => {\n"
"        const matchesQuery = s.studentId.toLowerCase().includes(query) || \n"
"                             s.name.toLowerCase().includes(query) || \n"
"                             s.course.toLowerCase().includes(query) || \n"
"                             s.hostelName.toLowerCase().includes(query);\n"
"        if (!matchesQuery) return false;\n"
"        \n"
"        if (filter === 'allotted') return s.isAllotted === 1;\n"
"        if (filter === 'unallotted') return s.isAllotted === 0;\n"
"        if (filter === 'defaulter') return s.isAllotted === 1 && s.feePending > 0;\n"
"        return true;\n"
"    });\n"
"    \n"
"    if (filtered.length === 0) {\n"
"        tbody.innerHTML = '<tr><td colspan=\"8\" class=\"text-center text-warning\">No matching students found.</td></tr>';\n"
"        return;\n"
"    }\n"
"    \n"
"    filtered.forEach(s => {\n"
"        const tr = document.createElement('tr');\n"
"        tr.innerHTML = `\n"
"            <td>${s.studentId}</td>\n"
"            <td>${s.name}</td>\n"
"            <td>${s.isAllotted ? s.hostelName : '<span class=\"text-warning\">None</span>'}</td>\n"
"            <td>${s.isAllotted ? s.roomNo : '-'}</td>\n"
"            <td>${s.isAllotted ? s.roomType : '-'}</td>\n"
"            <td class=\"text-success\">${s.isAllotted ? s.feePaid.toFixed(2) : '-'}</td>\n"
"            <td class=\"${s.isAllotted && s.feePending > 0 ? 'text-danger' : 'text-success'}\">${s.isAllotted ? s.feePending.toFixed(2) : '-'}</td>\n"
"            <td class=\"actions-flex\">\n"
"                <button class=\"btn-outline btn-sm\" onclick=\"showDossier('${s.studentId}')\">Dossier</button>\n"
"                ${s.isAllotted ? `\n"
"                    <button class=\"btn-outline btn-sm\" onclick=\"openTransferModal('${s.studentId}', '${s.name}', '${s.roomType}')\">Transfer</button>\n"
"                    <button class=\"btn-danger btn-sm\" onclick=\"openVacateModal('${s.studentId}', '${s.name}')\">Vacate</button>\n"
"                ` : ''}\n"
"            </td>\n"
"        `;\n"
"        tbody.appendChild(tr);\n"
"    });\n"
"}\n"
"\n"
"function renderRoomsGrid() {\n"
"    const selectedBlock = document.getElementById('room-block-select').value;\n"
"    const grid = document.getElementById('rooms-layout-grid');\n"
"    grid.innerHTML = '';\n"
"    \n"
"    let filtered = state.rooms.filter(r => r.hostelName === selectedBlock);\n"
"    \n"
"    filtered.forEach(r => {\n"
"        const card = document.createElement('div');\n"
"        let stateClass = '';\n"
"        let statusStr = '';\n"
"        \n"
"        if (r.isUnderMaintenance) {\n"
"            stateClass = 'state-maint';\n"
"            statusStr = 'Maintenance';\n"
"        } else if (r.occupancy >= r.capacity) {\n"
"            stateClass = 'state-full';\n"
"            statusStr = 'Full';\n"
"        } else {\n"
"            stateClass = 'state-vacant';\n"
"            statusStr = 'Vacant';\n"
"        }\n"
"        \n"
"        card.className = `room-card ${stateClass}`;\n"
"        \n"
"        // Find occupants\n"
"        let occupants = state.students.filter(s => s.isAllotted && s.hostelName === selectedBlock && s.roomNo === r.roomNo);\n"
"        let hoverTitle = occupants.map(s => s.name).join(', ') || 'No residents';\n"
"        \n"
"        card.title = `Residents: ${hoverTitle}`;\n"
"        \n"
"        card.innerHTML = `\n"
"            <div class=\"room-number\">Room ${r.roomNo}</div>\n"
"            <div class=\"room-type-badge\">${r.roomType}</div>\n"
"            <div class=\"room-occupancy-text\">Beds Occupied: ${r.occupancy}/${r.capacity}</div>\n"
"            <div style=\"font-size:12px; font-weight:600; margin-bottom:12px;\" class=\"${r.isUnderMaintenance ? 'text-danger' : (r.occupancy >= r.capacity ? 'text-warning' : 'text-success')}\">${statusStr}</div>\n"
"            <div style=\"display:flex; gap:6px; justify-content:center;\">\n"
"                <button class=\"btn-outline btn-sm\" onclick=\"toggleMaintenance('${r.hostelName}', '${r.roomNo}')\">Maint</button>\n"
"            </div>\n"
"        `;\n"
"        grid.appendChild(card);\n"
"    });\n"
"}\n"
"\n"
"function updateStudentAllotDropdown() {\n"
"    const select = document.getElementById('allot-student-select');\n"
"    select.innerHTML = '<option value=\"\">-- Select Unallotted Student --</option>';\n"
"    \n"
"    let unallotted = state.students.filter(s => s.isAllotted === 0);\n"
"    unallotted.forEach(s => {\n"
"        select.innerHTML += `<option value=\"${s.studentId}\">${s.studentId} - ${s.name}</option>`;\n"
"    });\n"
"}\n"
"\n"
"function updateAllotRoomDropdown() {\n"
"    const block = document.getElementById('allot-block-select').value;\n"
"    const type = document.getElementById('allot-type-select').value;\n"
"    const select = document.getElementById('allot-room-select');\n"
"    \n"
"    select.innerHTML = '<option value=\"\">-- Select Room --</option>';\n"
"    \n"
"    let available = state.rooms.filter(r => r.hostelName === block && r.roomType === type && r.occupancy < r.capacity && r.isUnderMaintenance === 0);\n"
"    \n"
"    available.forEach(r => {\n"
"        select.innerHTML += `<option value=\"${r.roomNo}\">Room ${r.roomNo} (Occupied: ${r.occupancy}/${r.capacity})</option>`;\n"
"    });\n"
"}\n"
"\n"
"function updateTransferRoomDropdown() {\n"
"    const block = document.getElementById('xfr-block-select').value;\n"
"    const type = document.getElementById('xfr-type-select').value;\n"
"    const select = document.getElementById('xfr-room-select');\n"
"    \n"
"    select.innerHTML = '<option value=\"\">-- Select Room --</option>';\n"
"    \n"
"    let available = state.rooms.filter(r => r.hostelName === block && r.roomType === type && r.occupancy < r.capacity && r.isUnderMaintenance === 0);\n"
"    \n"
"    available.forEach(r => {\n"
"        select.innerHTML += `<option value=\"${r.roomNo}\">Room ${r.roomNo} (Occupied: ${r.occupancy}/${r.capacity})</option>`;\n"
"    });\n"
"}\n"
"\n"
"// Event Handlers\n"
"function handleLogin(e) {\n"
"    e.preventDefault();\n"
"    const user = document.getElementById('username').value;\n"
"    const pass = document.getElementById('password').value;\n"
"    \n"
"    fetch(`/api/login?user=${encodeURIComponent(user)}&pass=${encodeURIComponent(pass)}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                state.user = user;\n"
"                localStorage.setItem('dynasty_admin', user);\n"
"                showAppScreen();\n"
"                document.getElementById('login-error').classList.add('hide');\n"
"            } else {\n"
"                document.getElementById('login-error').classList.remove('hide');\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function handleLogout() {\n"
"    localStorage.removeItem('dynasty_admin');\n"
"    state.user = null;\n"
"    showLoginScreen();\n"
"}\n"
"\n"
"function handleShutdown() {\n"
"    if (confirm('Are you sure you want to stop the server? This will terminate the web dashboard and return control to the C CLI Console.')) {\n"
"        fetch('/api/shutdown', { method: 'POST' })\n"
"            .then(() => {\n"
"                document.body.innerHTML = `\n"
"                    <div style=\"display:flex; justify-content:center; align-items:center; min-height:100vh; flex-direction:column;\">\n"
"                        <h1 style=\"color:#ef4444; margin-bottom:12px;\">Web Console Disconnected</h1>\n"
"                        <p style=\"color:#cbd5e1;\">The local C socket listener has shut down successfully.</p>\n"
"                        <p style=\"color:#94a3b8; font-size:12px; margin-top:12px;\">You may return to the console application safely.</p>\n"
"                    </div>\n"
"                `;\n"
"            });\n"
"    }\n"
"}\n"
"\n"
"function handleRegister(e) {\n"
"    e.preventDefault();\n"
"    \n"
"    const params = new URLSearchParams({\n"
"        name: document.getElementById('reg-name').value,\n"
"        dob: document.getElementById('reg-dob').value,\n"
"        gender: document.getElementById('reg-gender').value,\n"
"        aadhar: document.getElementById('reg-aadhar').value,\n"
"        blood: document.getElementById('reg-blood').value,\n"
"        nationality: document.getElementById('reg-nationality').value,\n"
"        email: document.getElementById('reg-email').value,\n"
"        phone: document.getElementById('reg-phone').value,\n"
"        religion: document.getElementById('reg-religion').value,\n"
"        caste: document.getElementById('reg-caste').value,\n"
"        course: document.getElementById('reg-course').value,\n"
"        branch: document.getElementById('reg-branch').value,\n"
"        semester: document.getElementById('reg-semester').value,\n"
"        roll: document.getElementById('reg-roll').value,\n"
"        father: document.getElementById('reg-father').value,\n"
"        mother: document.getElementById('reg-mother').value,\n"
"        parentPhone: document.getElementById('reg-parent-phone').value,\n"
"        parentEmail: document.getElementById('reg-parent-email').value,\n"
"        parentOcc: document.getElementById('reg-parent-occ').value,\n"
"        parentIncome: document.getElementById('reg-parent-income').value,\n"
"        guardName: document.getElementById('reg-guard-name').value,\n"
"        guardRel: document.getElementById('reg-guard-rel').value,\n"
"        guardPhone: document.getElementById('reg-guard-phone').value,\n"
"        guardAddr: document.getElementById('reg-guard-addr').value,\n"
"        addr: document.getElementById('reg-addr').value,\n"
"        city: document.getElementById('reg-city').value,\n"
"        state: document.getElementById('reg-state').value,\n"
"        pincode: document.getElementById('reg-pincode').value\n"
"    });\n"
"    \n"
"    fetch(`/api/students/add?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert(`Success! Student registered with ID: ${data.studentId}`);\n"
"                document.getElementById('register-form').reset();\n"
"                loadStudents();\n"
"            } else {\n"
"                alert(`Error: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function handleAllot(e) {\n"
"    e.preventDefault();\n"
"    \n"
"    const studentId = document.getElementById('allot-student-select').value;\n"
"    const hostelName = document.getElementById('allot-block-select').value;\n"
"    const roomNo = document.getElementById('allot-room-select').value;\n"
"    const date = document.getElementById('allot-date').value;\n"
"    const paid = document.getElementById('allot-paid').value;\n"
"    \n"
"    if (!studentId || !roomNo) {\n"
"        alert('Please select a student and available room.');\n"
"        return;\n"
"    }\n"
"\n"
"    const params = new URLSearchParams({ studentId, hostelName, roomNo, date, paid });\n"
"    \n"
"    fetch(`/api/allot?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert('Room allotted successfully!');\n"
"                document.getElementById('allot-form').reset();\n"
"                loadStudents();\n"
"                loadRooms();\n"
"            } else {\n"
"                alert(`Allotment failed: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function openTransferModal(studentId, name, roomType) {\n"
"    document.getElementById('xfr-student-id').value = studentId;\n"
"    document.getElementById('xfr-student-display').innerText = `${studentId} - ${name}`;\n"
"    document.getElementById('xfr-type-select').value = roomType;\n"
"    document.getElementById('transfer-modal').classList.remove('hide');\n"
"    updateTransferRoomDropdown();\n"
"}\n"
"\n"
"function closeTransfer() {\n"
"    document.getElementById('transfer-modal').classList.add('hide');\n"
"    document.getElementById('transfer-modal-form').reset();\n"
"}\n"
"\n"
"function handleTransfer(e) {\n"
"    e.preventDefault();\n"
"    const studentId = document.getElementById('xfr-student-id').value;\n"
"    const hostelName = document.getElementById('xfr-block-select').value;\n"
"    const roomNo = document.getElementById('xfr-room-select').value;\n"
"    const type = document.getElementById('xfr-type-select').value;\n"
"    \n"
"    if (!roomNo) {\n"
"        alert('Select a new available room.');\n"
"        return;\n"
"    }\n"
"    \n"
"    const params = new URLSearchParams({ studentId, hostelName, roomNo, type });\n"
"    \n"
"    fetch(`/api/transfer?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert('Student transferred successfully!');\n"
"                closeTransfer();\n"
"                loadStudents();\n"
"                loadRooms();\n"
"            } else {\n"
"                alert(`Transfer failed: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function openVacateModal(studentId, name) {\n"
"    document.getElementById('vac-student-id').value = studentId;\n"
"    document.getElementById('vac-student-display').innerText = `${studentId} - ${name}`;\n"
"    document.getElementById('vacate-modal').classList.remove('hide');\n"
"}\n"
"\n"
"function closeVacate() {\n"
"    document.getElementById('vacate-modal').classList.add('hide');\n"
"    document.getElementById('vacate-modal-form').reset();\n"
"}\n"
"\n"
"function handleVacate(e) {\n"
"    e.preventDefault();\n"
"    const studentId = document.getElementById('vac-student-id').value;\n"
"    const date = document.getElementById('vac-date').value;\n"
"    \n"
"    const params = new URLSearchParams({ studentId, date });\n"
"    \n"
"    fetch(`/api/vacate?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert('Student vacated successfully!');\n"
"                closeVacate();\n"
"                loadStudents();\n"
"                loadRooms();\n"
"            } else {\n"
"                alert(`Vacation failed: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function toggleMaintenance(hostelName, roomNo) {\n"
"    const params = new URLSearchParams({ hostelName, roomNo });\n"
"    fetch(`/api/maintenance?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert('Room maintenance status updated!');\n"
"                loadRooms();\n"
"            } else {\n"
"                alert(`Error: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function handleConfigUpdate(e) {\n"
"    e.preventDefault();\n"
"    const feeSingle = document.getElementById('cfg-single').value;\n"
"    const feeDouble = document.getElementById('cfg-double').value;\n"
"    const feeTriple = document.getElementById('cfg-triple').value;\n"
"    \n"
"    const params = new URLSearchParams({ feeSingle, feeDouble, feeTriple });\n"
"    fetch(`/api/config/update?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert('Configurations saved successfully!');\n"
"                loadConfigData();\n"
"            } else {\n"
"                alert(`Failed to save configuration: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function handlePasswordChange(e) {\n"
"    e.preventDefault();\n"
"    const currentPass = document.getElementById('pwd-current').value;\n"
"    const newPass = document.getElementById('pwd-new').value;\n"
"    const confirmPass = document.getElementById('pwd-confirm').value;\n"
"    \n"
"    if (newPass.length < 6) {\n"
"        alert('New password must be at least 6 characters.');\n"
"        return;\n"
"    }\n"
"    if (newPass !== confirmPass) {\n"
"        alert('Confirm password mismatch!');\n"
"        return;\n"
"    }\n"
"    \n"
"    const params = new URLSearchParams({ currentPass, newPass });\n"
"    fetch(`/api/password/change?${params.toString()}`, { method: 'POST' })\n"
"        .then(res => res.json())\n"
"        .then(data => {\n"
"            if (data.success) {\n"
"                alert('Password modified successfully!');\n"
"                document.getElementById('password-form').reset();\n"
"            } else {\n"
"                alert(`Error: ${data.message}`);\n"
"            }\n"
"        });\n"
"}\n"
"\n"
"function handleDatabaseWipe() {\n"
"    const confirmText = prompt('CRITICAL: This wipes all databases. Reverts credentials back to default admin/password123. Type \"WIPE\" to proceed:');\n"
"    if (confirmText === 'WIPE') {\n"
"        fetch('/api/reset', { method: 'POST' })\n"
"            .then(res => res.json())\n"
"            .then(data => {\n"
"                if (data.success) {\n"
"                    alert('Database wiped completely. You will be logged out.');\n"
"                    handleLogout();\n"
"                } else {\n"
"                    alert(`Wipe failed: ${data.message}`);\n"
"                }\n"
"            });\n"
"    }\n"
"}\n"
"\n"
"// Detailed Profile card rendering\n"
"function showDossier(studentId) {\n"
"    const s = state.students.find(x => x.studentId === studentId);\n"
"    if (!s) return;\n"
"    \n"
"    const body = document.getElementById('dossier-body-content');\n"
"    body.innerHTML = `\n"
"        <div class=\"dos-section\">\n"
"            <div class=\"dos-section-title\">1. Personal Information</div>\n"
"            <div class=\"dos-grid-3\">\n"
"                <div><span class=\"dos-lbl\">Name:</span> <span class=\"dos-val\">${s.name}</span></div>\n"
"                <div><span class=\"dos-lbl\">DOB:</span> <span class=\"dos-val\">${s.dob}</span></div>\n"
"                <div><span class=\"dos-lbl\">Gender:</span> <span class=\"dos-val\">${s.gender}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Aadhar Number:</span> <span class=\"dos-val\">${s.aadhar}</span></div>\n"
"                <div><span class=\"dos-lbl\">Blood Group:</span> <span class=\"dos-val\">${s.bloodGroup}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-3\">\n"
"                <div><span class=\"dos-lbl\">Nationality:</span> <span class=\"dos-val\">${s.nationality}</span></div>\n"
"                <div><span class=\"dos-lbl\">Religion:</span> <span class=\"dos-val\">${s.religion}</span></div>\n"
"                <div><span class=\"dos-lbl\">Caste Category:</span> <span class=\"dos-val\">${s.caste}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Email Address:</span> <span class=\"dos-val\">${s.email}</span></div>\n"
"                <div><span class=\"dos-lbl\">Phone Number:</span> <span class=\"dos-val\">${s.phone}</span></div>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <div class=\"dos-section\">\n"
"            <div class=\"dos-section-title\">2. Academic Details</div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Course Program:</span> <span class=\"dos-val\">${s.course}</span></div>\n"
"                <div><span class=\"dos-lbl\">Department/Branch:</span> <span class=\"dos-val\">${s.branch}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Current Semester:</span> <span class=\"dos-val\">${s.semester}</span></div>\n"
"                <div><span class=\"dos-lbl\">University Roll No:</span> <span class=\"dos-val\">${s.rollNo}</span></div>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <div class=\"dos-section\">\n"
"            <div class=\"dos-section-title\">3. Parent & Guardian Details</div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Father's Name:</span> <span class=\"dos-val\">${s.fatherName}</span></div>\n"
"                <div><span class=\"dos-lbl\">Mother's Name:</span> <span class=\"dos-val\">${s.motherName}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Parent Phone:</span> <span class=\"dos-val\">${s.parentPhone}</span></div>\n"
"                <div><span class=\"dos-lbl\">Parent Email:</span> <span class=\"dos-val\">${s.parentEmail}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Parent Occupation:</span> <span class=\"dos-val\">${s.parentOccupation}</span></div>\n"
"                <div><span class=\"dos-lbl\">Annual Family Income:</span> <span class=\"dos-val\">INR ${s.parentIncome}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-2\">\n"
"                <div><span class=\"dos-lbl\">Guardian Name:</span> <span class=\"dos-val\">${s.guardianName} (${s.guardianRelation})</span></div>\n"
"                <div><span class=\"dos-lbl\">Guardian Contact:</span> <span class=\"dos-val\">${s.guardianPhone}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-1\">\n"
"                <div><span class=\"dos-lbl\">Guardian Address:</span> <span class=\"dos-val\">${s.guardianAddress}</span></div>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div class=\"dos-section\">\n"
"            <div class=\"dos-section-title\">4. Permanent Address</div>\n"
"            <div class=\"dos-grid-1\">\n"
"                <div><span class=\"dos-lbl\">Street Details:</span> <span class=\"dos-val\">${s.permanentAddress}</span></div>\n"
"            </div>\n"
"            <div class=\"dos-grid-3\">\n"
"                <div><span class=\"dos-lbl\">City:</span> <span class=\"dos-val\">${s.city}</span></div>\n"
"                <div><span class=\"dos-lbl\">State:</span> <span class=\"dos-val\">${s.state}</span></div>\n"
"                <div><span class=\"dos-lbl\">Pincode:</span> <span class=\"dos-val\">${s.pincode}</span></div>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div class=\"dos-section\">\n"
"            <div class=\"dos-section-title\">5. Room Allotment Metadata</div>\n"
"            ${s.isAllotted ? `\n"
"                <div class=\"dos-grid-3\">\n"
"                    <div><span class=\"dos-lbl\">Hostel Dynasty:</span> <span class=\"dos-val\">${s.hostelName}</span></div>\n"
"                    <div><span class=\"dos-lbl\">Room Number:</span> <span class=\"dos-val\">Room ${s.roomNo}</span></div>\n"
"                    <div><span class=\"dos-lbl\">Bed Occupancy:</span> <span class=\"dos-val\">${s.roomType}</span></div>\n"
"                </div>\n"
"                <div class=\"dos-grid-3\">\n"
"                    <div><span class=\"dos-lbl\">Date Allotted:</span> <span class=\"dos-val\">${s.allotmentDate}</span></div>\n"
"                    <div><span class=\"dos-lbl\">Total Fees Paid:</span> <span class=\"dos-val text-success\">INR ${s.feePaid.toFixed(2)}</span></div>\n"
"                    <div><span class=\"dos-lbl\">Pending Balance:</span> <span class=\"dos-val ${s.feePending > 0 ? 'text-danger' : 'text-success'}\">INR ${s.feePending.toFixed(2)}</span></div>\n"
"                </div>\n"
"            ` : `\n"
"                <div class=\"text-warning\" style=\"font-size:13px;\">\n"
"                    Student is currently not allotted to any block.\n"
"                    ${s.checkoutDate ? `(Checkout date registered on: ${s.checkoutDate})` : ''}\n"
"                </div>\n"
"            `}\n"
"        </div>\n"
"    `;\n"
"    document.getElementById('dossier-modal').classList.remove('hide');\n"
"}\n"
"\n"
"function closeDossier() {\n"
"    document.getElementById('dossier-modal').classList.add('hide');\n"
"}\n"
"";

#endif /* WEB_ASSETS_H */
